# Generated by Django 2.1.3 on 2018-11-19 21:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sauna_occupancies', '0003_auto_20181119_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupancy',
            name='user',
        ),
        migrations.AddField(
            model_name='occupancy',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
