# Generated by Django 2.1.3 on 2018-11-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauna_occupancies', '0005_auto_20181119_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupancy',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
